#!/bin/sh
set -eu

if [ "$#" -eq 0 ]; then
  echo "Usage: nvidia-run command [arguments...]" >&2
  exit 2
fi

exec env \
  __NV_PRIME_RENDER_OFFLOAD=1 \
  __GLX_VENDOR_LIBRARY_NAME=nvidia \
  __VK_LAYER_NV_optimus=NVIDIA_only \
  "$@"
